### ISSUE TITLE
Image-Model does not support TYPO3\CMS\Extbase\Domain\Model\FileReference

### ISSUE THREAD

**Issue by infabo** [sitegeist/fluid-components#38]
Unfortunately it is currently not possible to pass `TYPO3\CMS\Extbase\Domain\Model\FileReference` for props typed as `SMS\FluidComponents\Domain\Model\Image`.

Is it planned in the future?

**Comment by s2b** [comment]
Thank your for your feedback! Currently this is not planned because I'm not sure if I want to add the dependency of Extbase to the extension. However, you can just use `.originalResource` when calling the component, which returns a core file reference.

```xml
<my:component image="{image.getOriginalResource}" />
```

**Comment by infabo** [comment]
Thanks @s2b for the feedback! Yes, I am aware of the "workaround" with `originalResource`. But this is not possible, if you have 

`<fc:param name="files" type="\SMS\FluidComponents\Domain\Model\Image[]"/>`

for example. A generic "type=array" would work, but everybody should clearly see whats the component expects, when looking at the props.

**Comment by s2b** [comment]
Good point! I'll add it to the ToDo list. 👍 

Did you test this example? I'm not sure that the array syntax `[]` works with automatic conversion yet.

**Comment by infabo** [comment]
Already successfully using this array syntax.

**Comment by s2b** [comment]
Could you test if #45 solves your issue?

**Comment by s2b** [comment]
Is now part of v2.0. Feel free to open a new issue if the problem still persists.
