### ISSUE TITLE
Default of boolean param results in Exception

### ISSUE THREAD

**Issue by cpotemski** [sitegeist/fluid-components#4]
If I try to define a boolean param like one of this...
```xml
<fc:param name="disabled" type="boolean" optional="1" default="0" />
<fc:param name="disabled" type="boolean" optional="1" default="FALSE" />
<fc:param name="disabled" type="boolean" optional="1" default="false" />
```

... I get an exception from TYPO3
```
The argument "disabled" was registered with type "boolean", but is of type "NULL" in component
```

Is this a bug or am I doing it the wrong way?

**Comment by cpotemski** [comment]
I don't know if this is related, but when I use following param
```xml
<fc:param name="max" type="number" optional="1" default="100" />
```
uncached => everything is fine and like excepted (value = 100 if no value is set)
cached => param "max" is empty

**Comment by s2b** [comment]
Your first problem should be fixed with branch `/bugfix/defaultBooleanValue`. Could you verify this?

**Comment by cpotemski** [comment]
I can verify this. Now the default values work like expected
