### ISSUE TITLE
Underscored parameters aren't working

### ISSUE THREAD

**Issue by janhelke** [sitegeist/fluid-components#5]
If you define a component having parameters with underscores in the name, the rendering is failing.

If you need to call a component like
`<foo:bar.baz
    foo_bar="baz"
/>`
the output in the HTML source will be exactly that.

If you can call it like 
`<foo:bar.baz
    foo-bar="baz"
/>`
the rendering works perfect.

I'm not sure, if that is a flaw of the extension or of HTML or somewhere else. But at least it should be documented somewhere.

**Comment by s2b** [comment]
This seems to be a limitation of Fluid:
https://github.com/TYPO3/Fluid/blob/master/src/Core/Parser/Patterns.php#L56
