### ISSUE TITLE
Using f:section inside fc:renderer

### ISSUE THREAD

**Issue by georgringer** [sitegeist/fluid-components#52]
Is it possible to use `<f:switch>` inside the `<fc:renderer>` viewhelper.

example
```
<f:section name="type">
    <f:spaceless>
        <f:switch expression="{type}">
            <f:case value="info">border-blue-400 text-blue-700</f:case>
            <f:case value="danger">border-red-400 text-red-700</f:case>
        </f:switch>
    </f:spaceless>
</f:section>
```

**Comment by s2b** [comment]
Yes, this is possible. I think that the issue comes from `<f:section>` which isn't properly supported in components.

**Comment by georgringer** [comment]
Yes of course, sorry, meant f:section. In the example I use this to generate css classes but I really don't want to put the tag based VHs into the markup

**Comment by s2b** [comment]
You could easily substitute the section with `<f:variable name="typeClass">...</f:variable>`.

During the initial development of the extensions, I tried to get sections working but wasn't successful because there are no suitable hooking points.
