### ISSUE TITLE
Feature: Add label and description to FieldInformationViewHelper 

### ISSUE THREAD

**Issue by katywings** [sitegeist/fluid-components#71]
IS:
As mentioned via Slack, [FieldInformationViewHelper](https://github.com/sitegeist/fluid-components/blob/03ee915a93acb3a1f005589b2f05ec3e719a297d/Classes/ViewHelpers/Form/FieldInformationViewHelper.php#L36) currently doesn't include the form field properties "label" and "description". 

SHOULD:
Would be awesome to get those "label" and "description" properties in the FIeldInformationViewHelper as well - maybe there are even more that could be included by default?

**Comment by s2b** [comment]
Thank you for the suggestion. :) I just looked into it and also checked how we solved this in our `EXT:form` forms:

```xml
<fc:form.translatedValidationResults element="{element}" as="validationResults">
    <fc:form.fieldInformation
        as="field"
        property="{element.identifier}"
        additionalAttributes="{formvh:translateElementProperty(element: element, property: 'fluidAdditionalAttributes')}"
    >
        <my:molecule.formField
            class="{element.properties.elementClassAttribute}"
            label="{formvh:translateElementProperty(element: element, property: 'label')}"
            validationResults="{validationResults}"
            isRequired="{field.additionalAttributes.required}"
            description="{formvh:translateElementProperty(element: element, property: 'elementDescription')}"
        >
            <my:atom.input
                hasError="{validationResults.hasErrors}"
                isRequired="{field.additionalAttributes.required}"
                name="{field.name}"
                placeholder="{field.additionalAttributes.placeholder}"
                type="email"
                value="{field.value}"
            />
        </my:molecule.formField>
    </fc:form.fieldInformation>
</fc:form.translatedValidationResults>
```

Relevant lines:

```xml
            label="{formvh:translateElementProperty(element: element, property: 'label')}"
            description="{formvh:translateElementProperty(element: element, property: 'elementDescription')}"
```

As you can see there, we still use the ViewHelpers included in `EXT:form` to take care of the translations. That's the reason why the ViewHelper doesn't provide `label` and `description`. But as you can see in the example, it's possible to use the values in the template directly.

Does that resolve your request or did I misunderstand?

**Comment by katywings** [comment]
Good morning @s2b

Thank you a lot for the detailed explanation, `{formvh:translateElementProperty(element: element, property: 'label')}` thats exactly how I am solving it too at the moment :). 

Tbh I created this feature request, not because I was in the need of a workaround :D, but because it seemed this might be a great addition to the `fieldInformation` viewhelper - so that all generally used field properties can be easily accessed without many manual translation calls.

**Comment by Atomschinken** [comment]
I'm closing this issue for now.
Please feel free to reopen it if necessary.
