### ISSUE TITLE
Compatibility with TYPO3 11.3

### ISSUE THREAD

**Issue by cheindl** [sitegeist/fluid-components#85]
Due to internal changes in `\TYPO3\CMS\Fluid\Core\ViewHelper\ViewHelperResolver` for TYPO3 11.3 fluid_components cannot work like expected anymore.
Directly after upgrading to 11.3 the following error occurred, when opening the website:

> Fatal error: Declaration of SMS\FluidComponents\Fluid\ViewHelper\ViewHelperResolver::createViewHelperInstanceFromClassName($viewHelperClassName) must be compatible with TYPO3\CMS\Fluid\Core\ViewHelper\ViewHelperResolver::createViewHelperInstanceFromClassName($viewHelperClassName): TYPO3Fluid\Fluid\Core\ViewHelper\ViewHelperInterface in /app/public/typo3conf/ext/fluid_components/Classes/Fluid/ViewHelper/ViewHelperResolver.php on line 16

After making the declaration compatible with its superclass an error still occurs: The base class is now created by a custom factory class (`\TYPO3\CMS\Fluid\Core\ViewHelper\ViewHelperResolverFactory`), which does not honor the overridden ViewHelperResolver (`$GLOBALS['TYPO3_CONF_VARS']['SYS']['Objects']....`) class. Thus the creation of ViewHelperResolver is now inconsistent between TYPO3 core and fluid_components.

**Comment by s2b** [comment]
Thank you for bringing this to my attention. I'll look into it as soon as possible.

**Comment by s2b** [comment]
https://github.com/TYPO3/typo3/commit/669ab6384c4c853e78db77f72bca120dfa0d0e91

**Comment by s2b** [comment]
We will be able to fix this with the release of TYPO3 11.4. We are already in contact with the TYPO3 core team to ship the required core patch.

https://review.typo3.org/c/Packages/TYPO3.CMS/+/70831

A pull request (#86) for Fluid Components is almost ready. It will most likely drop support for TYPO3 9 but will stay compatible with TYPO3 10.

**Comment by s2b** [comment]
The new version has been released.
